---
name: mycicd

on:
  push:
    branches:
      - main

jobs: 
  pullcicd:
    runs-on: ubuntu-latest
    steps:
      - name: workflow started
        run: echo "Workflow started"

      - name: ssh into server
        run: | 
          echo "This step will always run"
        
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          cat SSH_KEY > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "ec2-13-232-47-69.ap-south-1.compute.amazonaws.com"
            User cicd
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Running gitpull
        run: ssh staging 'bash /var/www/cicd.sh'

      - name: workflow completed
        run: echo "check server output" 

